### ISSUE TITLE
Ошибка MediaManager 

### ISSUE THREAD

**Issue by Spb-Webmaster** [yurizoom/moonshine-media-manager#4]
Здравствуйте. Очень хочу установить ваш MediaManagerPage, но на вcех проектах одна и таже ошибка.
При заходе на страницу медиа менеджера.
"Method Illuminate\Routing\UrlGenerator::query does not exist." Откуда у класса UrlGenerator такой метод?
Laravel 10, php 8.2, Moonshine  "^2.7" (пробовал разные версии).
![2024-09-30_11-02-08](https://github.com/user-attachments/assets/0a45b376-0abc-4696-b19f-75eb99fabc6c)

**Comment by yurizoom** [comment]
Здравствуйте! Данные метод появился в Laravel 11 (https://laravel.com/api/11.x/Illuminate/Routing/UrlGenerator.html). Сейчас поправлю для поддержки Laravel 10

**Comment by Spb-Webmaster** [comment]
Спасибо!

**Comment by yurizoom** [comment]
попробуйте обновить до версии 1.2.0

**Comment by Spb-Webmaster** [comment]
Отлично! Обновил composer, все заработало. Спасибо.
